---
- hosts: db
  become: true
  gather_facts: true

  tasks:

  - name: start db load
    shell: nohup /home/ubuntu/dbload.sh &
    become: true
 
- hosts: web
  become: true
  gather_facts: true

  tasks:

  - name: start web load
    shell: nohup /home/ubuntu/webload.sh &
    become: true

- hosts: app
  become: true
  gather_facts: true

  tasks:

  - name: start trunc
    shell: nohup /home/ubuntu/appload.sh &
    become: true
  
